/**
 * API types for the Refyne SDK.
 *
 * These types are generated from the OpenAPI specification.
 * Do not edit this file manually - run `npm run generate` to regenerate.
 *
 * @packageDocumentation
 */

// ============================================================================
// Request Types
// ============================================================================

/**
 * Request body for data extraction.
 */
export interface ExtractRequest {
  /** URL to extract data from */
  url: string;
  /** Schema defining the data structure to extract */
  schema: Record<string, unknown>;
  /** Fetch mode: auto (detect), static (fast), or dynamic (JavaScript rendering) */
  fetchMode?: 'auto' | 'static' | 'dynamic';
  /** Custom LLM configuration */
  llmConfig?: LlmConfig;
}

/**
 * Request body for starting a crawl job.
 */
export interface CrawlRequest {
  /** Seed URL to start crawling from */
  url: string;
  /** Schema defining the data structure to extract */
  schema: Record<string, unknown>;
  /** Crawl options */
  options?: CrawlOptions;
  /** Webhook URL to receive completion notification */
  webhookUrl?: string;
  /** Custom LLM configuration */
  llmConfig?: LlmConfig;
}

/**
 * Options for crawl jobs.
 */
export interface CrawlOptions {
  /** CSS selector for links to follow */
  followSelector?: string;
  /** Regex pattern for URLs to follow */
  followPattern?: string;
  /** Maximum crawl depth (default: 1, max: 5) */
  maxDepth?: number;
  /** CSS selector for pagination next link */
  nextSelector?: string;
  /** Maximum pages to crawl (default: 10, max: 100) */
  maxPages?: number;
  /** Maximum total URLs to process (default: 50, max: 500) */
  maxUrls?: number;
  /** Delay between requests (default: "500ms") */
  delay?: string;
  /** Concurrent requests (default: 3, max: 10) */
  concurrency?: number;
  /** Only follow same-domain links (default: true) */
  sameDomainOnly?: boolean;
  /** Extract data from seed URLs */
  extractFromSeeds?: boolean;
}

/**
 * LLM provider configuration for extraction.
 */
export interface LlmConfig {
  /** LLM provider */
  provider?: 'anthropic' | 'openai' | 'openrouter' | 'ollama' | 'credits';
  /** API key for the provider (BYOK) */
  apiKey?: string;
  /** Custom base URL (for Ollama or self-hosted) */
  baseUrl?: string;
  /** Model to use */
  model?: string;
}

/**
 * Request body for website analysis.
 */
export interface AnalyzeRequest {
  /** URL to analyze */
  url: string;
  /** Analysis depth (default: 1) */
  depth?: number;
}

/**
 * Request body for creating a schema.
 */
export interface CreateSchemaRequest {
  /** Schema name */
  name: string;
  /** Schema description */
  description?: string;
  /** Schema definition in YAML format */
  schemaYaml: string;
  /** Category for organization */
  category?: string;
}

/**
 * Request body for creating a saved site.
 */
export interface CreateSiteRequest {
  /** Site name */
  name: string;
  /** Site URL */
  url: string;
  /** Associated schema ID */
  schemaId?: string;
  /** Default crawl options */
  crawlOptions?: CrawlOptions;
}

/**
 * Request body for creating an API key.
 */
export interface CreateApiKeyRequest {
  /** Name for the API key */
  name: string;
}

/**
 * Request body for upserting an LLM provider key.
 */
export interface UpsertLlmKeyRequest {
  /** Provider name */
  provider: 'anthropic' | 'openai' | 'openrouter' | 'ollama';
  /** API key */
  apiKey: string;
  /** Default model for this provider */
  defaultModel: string;
  /** Custom base URL */
  baseUrl?: string;
  /** Whether the key is enabled */
  isEnabled?: boolean;
}

/**
 * Request body for setting the fallback chain.
 */
export interface SetLlmChainRequest {
  /** Ordered list of fallback entries */
  chain: LlmChainEntry[];
}

// ============================================================================
// Response Types
// ============================================================================

/**
 * Response from data extraction.
 */
export interface ExtractResponse {
  /** Extracted data matching the schema */
  data: Record<string, unknown>;
  /** URL that was extracted */
  url: string;
  /** Timestamp when the page was fetched */
  fetchedAt: string;
  /** Token usage information */
  usage?: TokenUsage;
  /** Extraction metadata */
  metadata?: ExtractionMetadata;
}

/**
 * Token usage information from extraction.
 */
export interface TokenUsage {
  /** Number of input tokens used */
  inputTokens: number;
  /** Number of output tokens used */
  outputTokens: number;
  /** Total USD cost charged */
  costUsd: number;
  /** Actual LLM cost from provider */
  llmCostUsd: number;
  /** True if user's own API key was used */
  isByok: boolean;
}

/**
 * Metadata from extraction.
 */
export interface ExtractionMetadata {
  /** Time to fetch the page in milliseconds */
  fetchDurationMs: number;
  /** Time to extract data in milliseconds */
  extractDurationMs: number;
  /** Model used for extraction */
  model: string;
  /** LLM provider used */
  provider: string;
}

/**
 * Response when a crawl job is created.
 */
export interface CrawlJobCreated {
  /** Unique job identifier */
  jobId: string;
  /** Initial job status */
  status: JobStatus;
  /** URL to check job status */
  statusUrl: string;
}

/**
 * Job status enum.
 */
export type JobStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * Job details.
 */
export interface Job {
  /** Job ID */
  id: string;
  /** Job type */
  type: string;
  /** Current status */
  status: JobStatus;
  /** Seed URL */
  url: string;
  /** Number of URLs queued */
  urls_queued: number;
  /** Number of pages processed */
  page_count: number;
  /** Input tokens used */
  token_usage_input: number;
  /** Output tokens used */
  token_usage_output: number;
  /** Cost in USD */
  cost_usd: number;
  /** Error message if failed */
  error_message?: string;
  /** When the job started */
  started_at?: string;
  /** When the job completed */
  completed_at?: string;
  /** When the job was created */
  created_at: string;
}

/**
 * List of jobs response.
 */
export interface JobList {
  /** List of jobs */
  jobs: Job[];
}

/**
 * Job results response.
 */
export interface JobResults {
  /** Job ID */
  jobId: string;
  /** Job status */
  status: JobStatus;
  /** Array of extraction results (when merge=false) */
  results?: Array<Record<string, unknown>>;
  /** Merged results object (when merge=true) */
  merged?: Record<string, unknown>;
  /** Number of pages processed */
  pageCount: number;
}

/**
 * Response from website analysis.
 */
export interface AnalyzeResponse {
  /** URL that was analyzed */
  url: string;
  /** Suggested schema based on page content */
  suggestedSchema: Record<string, unknown>;
  /** Suggested URL patterns for crawling */
  followPatterns: string[];
}

/**
 * Schema definition.
 */
export interface Schema {
  /** Schema ID */
  id: string;
  /** Schema name */
  name: string;
  /** Schema description */
  description?: string;
  /** Schema definition in YAML */
  schemaYaml: string;
  /** Category */
  category?: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * List of schemas.
 */
export interface SchemaList {
  /** List of schemas */
  schemas: Schema[];
}

/**
 * Saved site configuration.
 */
export interface Site {
  /** Site ID */
  id: string;
  /** Site name */
  name: string;
  /** Site URL */
  url: string;
  /** Associated schema ID */
  schemaId?: string;
  /** Default crawl options */
  crawlOptions?: CrawlOptions;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * List of saved sites.
 */
export interface SiteList {
  /** List of sites */
  sites: Site[];
}

/**
 * API key (without the secret).
 */
export interface ApiKey {
  /** Key ID */
  id: string;
  /** Key name */
  name: string;
  /** Key prefix for identification */
  prefix: string;
  /** Creation timestamp */
  createdAt: string;
  /** Last used timestamp */
  lastUsedAt?: string;
}

/**
 * Newly created API key (includes the full key).
 */
export interface ApiKeyCreated {
  /** Key ID */
  id: string;
  /** Key name */
  name: string;
  /** Full API key - only shown once */
  key: string;
}

/**
 * List of API keys.
 */
export interface ApiKeyList {
  /** List of keys */
  keys: ApiKey[];
}

/**
 * Usage statistics.
 */
export interface UsageResponse {
  /** Total number of jobs */
  total_jobs: number;
  /** Total USD charged for usage */
  total_charged_usd: number;
  /** Jobs using user's own API keys (not charged) */
  byok_jobs: number;
}

/**
 * LLM provider key configuration.
 */
export interface LlmKey {
  /** Key ID */
  id: string;
  /** Provider name */
  provider: string;
  /** Default model */
  defaultModel: string;
  /** Custom base URL */
  baseUrl?: string;
  /** Whether the key is enabled */
  isEnabled: boolean;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * List of LLM provider keys.
 */
export interface LlmKeyList {
  /** List of keys */
  keys: LlmKey[];
}

/**
 * Entry in the LLM fallback chain.
 */
export interface LlmChainEntry {
  /** Entry ID */
  id?: string;
  /** Position in chain */
  position?: number;
  /** Provider name */
  provider: string;
  /** Model name */
  model: string;
  /** Whether this entry is enabled */
  isEnabled?: boolean;
}

/**
 * LLM fallback chain.
 */
export interface LlmChain {
  /** Ordered chain entries */
  chain: LlmChainEntry[];
}

/**
 * Available model.
 */
export interface Model {
  /** Model ID */
  id: string;
  /** Model display name */
  name: string;
}

/**
 * List of available models.
 */
export interface ModelList {
  /** List of models */
  models: Model[];
}

/**
 * Health check response.
 */
export interface HealthResponse {
  /** Status (always "ok" if healthy) */
  status: 'ok';
}

/**
 * API error response.
 */
export interface ErrorResponse {
  /** Error message */
  error: string;
  /** HTTP status code */
  status: number;
  /** Additional error detail */
  detail?: string;
}

// ============================================================================
// Streaming Types
// ============================================================================

/**
 * Event types for SSE streaming.
 */
export type JobEventType =
  | 'status'
  | 'progress'
  | 'result'
  | 'error'
  | 'complete';

/**
 * Base job event.
 */
export interface BaseJobEvent {
  /** Event type */
  type: JobEventType;
  /** Event timestamp */
  timestamp: string;
}

/**
 * Job status change event.
 */
export interface JobStatusEvent extends BaseJobEvent {
  type: 'status';
  /** New status */
  status: JobStatus;
}

/**
 * Job progress event.
 */
export interface JobProgressEvent extends BaseJobEvent {
  type: 'progress';
  /** Number of pages processed */
  pagesProcessed: number;
  /** Total pages to process (if known) */
  totalPages?: number;
  /** Current URL being processed */
  currentUrl?: string;
}

/**
 * Individual result event.
 */
export interface JobResultEvent extends BaseJobEvent {
  type: 'result';
  /** URL the result is from */
  url: string;
  /** Extracted data */
  data: Record<string, unknown>;
}

/**
 * Job error event.
 */
export interface JobErrorEvent extends BaseJobEvent {
  type: 'error';
  /** Error message */
  message: string;
  /** URL that caused the error (if applicable) */
  url?: string;
}

/**
 * Job completion event.
 */
export interface JobCompleteEvent extends BaseJobEvent {
  type: 'complete';
  /** Final job status */
  status: JobStatus;
  /** Total pages processed */
  pageCount: number;
}

/**
 * Union of all job event types.
 */
export type JobEvent =
  | JobStatusEvent
  | JobProgressEvent
  | JobResultEvent
  | JobErrorEvent
  | JobCompleteEvent;
